### ISSUE TITLE
Failed to initialize secondary camera

### ISSUE THREAD

**Issue by baptistecaziot** [jbhunt/parallel-pyspin#1]
Hi.
I have issues opening a secondary camera. I am unfamiliar with multiprocessing and it looks like the error comes from that. Any hint on how to solve this issue?
Thanks a lot.

Here is the code:
`fps = 60
device1 = str(21187335)
device2 = str(21187339)
device3 = str(21187342)
print("camera 1: " + device1 + ", camera 2: " + device2 + ", camera 3: " + device3)
filename1 = 'test1.mp4'
filename2 = 'test2.mp4'
filename3 = 'test3.mp4'
print("Open primary camera")
cam1 = primary.PrimaryCamera(device1)
cam1.framerate = fps
print("framerate: " + str(cam1.framerate))
cam1.prime(filename1)
print("Open secondary cameras")
cam2 = secondary.SecondaryCamera(device2)
cam2.prime(filename2, cam1.framerate)
cam3 = secondary.SecondaryCamera(device3)
cam3.prime(filename3, fps)
cam1.trigger()`

Here is the error:
`camera 1: 21187335, camera 2: 21187339, camera 3: 21187342
Open primary camera
framerate: 59.96705170311224
Open secondary cameras
Traceback (most recent call last):
File "parallelpyspin_test.py", line 26, in <module>
    cam2 = secondary.SecondaryCamera(device2)
File "/.../anaconda3/lib/python3.8/site-packages/parallel_pyspin-1.0.0-py3.8.egg/llpyspin/secondary.py", line 19, in __init__
File "/.../anaconda3/lib/python3.8/site-packages/parallel_pyspin-1.0.0-py3.8.egg/llpyspin/processes.py", line 275, in _spawn_child_process
File "/.../anaconda3/lib/python3.8/site-packages/parallel_pyspin-1.0.0-py3.8.egg/llpyspin/processes.py", line 29, in wrapped
llpyspin.processes.CameraError: Failed to initialize camera`

And sometimes (but not always) I receive this error:
`Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 245, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipes`

**Comment by jbhunt** [comment]
Hello! Let me see if I can recreate this error on my machine. It would help if I have some more info about your setup:

1. How did you install the parallel-pyspin package? What version are you using?
2. What kind of OS are you using to operate the cameras?
3. What model of camera are you using?

**Comment by baptistecaziot** [comment]
Hi.
1. I'm pretty sure I used the python setup script. I tried to rerun it right now and I get the error: "Error while finding module specification for 'setup.py' (ModuleNotFoundError: __path__ attribute not found on 'setup' while trying to find 'setup.py')". But I assume it run correctly when I installed it. I don't entirely remember.
2. The computer has Ubuntu 20.04.
3. I use FLIR Blackfly S USB3 cameras (BFS-U3-16S2C-CS)

**Comment by jbhunt** [comment]
Awesome, thank you! I'll work on this today and try to get it fixed ASAP. I don't have this exact camera on hand so I might send you a couple scripts to run as tests if that's okay. It could be a difference in the color image-capable cameras vs. the monochrome cameras I used to develop this software with.

**Comment by baptistecaziot** [comment]
Ok. Thanks a lot for your help.

**Comment by baptistecaziot** [comment]
The issue was simply that the previously opened cameras (from pyspin or in spinview) have to be correctly closed in order to change the camera parameters.
